### ISSUE TITLE
Sitemap Not Available

### ISSUE THREAD

**Issue by ethanosullivan** [netlify-labs/netlify-plugin-sitemap#34]
I had an issue with my Sitemap with the recent update. It used to work before with my configuration in my `netlify.toml`.

When I tried to visit my sitemap, I would end up with a 404 page. Previously, I did not define the `buildDir` in the past because the default value worked for me. After reading issue #33, I set my `buildDir` to `"./"` and that loads my sitemap. However, it's blank.

I changed it to `buildDir = "publish"` [like the documentation](https://github.com/netlify-labs/netlify-plugin-sitemap#configuration), but I get the 404 again.

Here's my config:

```
# Sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "publish"
prettyURLs = true
trailingSlash = true
exclude = [
    "**/404.html"
]
```

Please let me know the default `buildDir` to use. I have my repo hosted on GitHub, but it's private.

**Comment by erezrokah** [comment]
Hi @ethanosullivan, where the html files for your site are located? Can you share the repo structure?

**Comment by ethanosullivan** [comment]
In the root of my GitHub repo, here's what it looks like:

![image](https://user-images.githubusercontent.com/23202467/98290964-65d61e80-1f78-11eb-9e66-9cb427d026bd.png)

**Comment by ethanosullivan** [comment]
Hey @erezrokah - just checking in on an update on this issue. I tried searching on Netlify what the correct `buildDir` should be, but I haven't found anything as of yet.

**Comment by erezrokah** [comment]
Sorry @ethanosullivan, missed your last comment. `buildDir` should point to the directory where your static HTML files are located. In your case I would try `buildDir: "."`

**Comment by ethanosullivan** [comment]
That seems to work. However, the `<loc>` tags are only showing my domain and not the full path to the URL. Here's what it looks like:

```xml
...
    <url>
        <loc>https://ethanosullivan.com/</loc>
        <lastmod>2020-11-09T14:01:05Z</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://ethanosullivan.com/</loc>
        <lastmod>2020-11-09T14:01:05Z</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://ethanosullivan.com/</loc>
        <lastmod>2020-11-09T14:01:05Z</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://ethanosullivan.com/</loc>
        <lastmod>2020-11-09T14:01:05Z</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
...
```

I do have 4 pages for my website, but you can see that it only shows the path as `https://ethanosullivan.com/`

**Comment by ethanosullivan** [comment]
Did you get a chance to see my last comment @erezrokah ?

**Comment by ethanosullivan** [comment]
Checking in again @erezrokah - any updates? This is broken on all of my sites that use this plugin

**Comment by erezrokah** [comment]
Sorry for the late reply @ethanosullivan.
Do you mind sharing a public repo reproducing this issue? It will make it easier to debug

**Comment by ethanosullivan** [comment]
Here you go @erezrokah:

https://github.com/ethanosullivan/example.com

I added a [dummy website](https://dazzling-kepler-408ea8.netlify.app/blog.html) with plenty of pages and the [sitemap plugin](https://github.com/ethanosullivan/example.com/blob/master/netlify.toml). You'll ee the results are the same.

**Comment by ethanosullivan** [comment]
While you're testing out my test repo, is there a way to run the plugin on a previous version that is working? I activate the plugin through the `netlify.toml` file and don't use any CLI to run my websites.

**Comment by erezrokah** [comment]
Hi @ethanosullivan, you can always install a specific plugin version via `npm install @netlify/plugin-sitemap@<version>` (e.g. `npm install @netlify/plugin-sitemap@v0.4.0`).

**Comment by ethanosullivan** [comment]
That requires commands (CLI) - there's no other way? How's the progress going with finding a solution?

**Comment by erezrokah** [comment]
Hi @ethanosullivan sorry for the delay, this should be fixed by https://github.com/netlify-labs/netlify-plugin-sitemap/pull/41

**Comment by ethanosullivan** [comment]
I republished my website with the following setitngs, but I still get the same issue:

```
# Sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "."
prettyURLs = true
trailingSlash = true
exclude = [
    "**/404.html"
]
```

Is there a specific value I should use for the `buildDir`?

**Comment by erezrokah** [comment]
> I republished my website with the following setitngs, but I still get the same issue:

Hi @ethanosullivan, there is a time gap (which we are working to fix) between publishing a new plugin version until it is available in our CI. I'll update this issue once the new version is available.

**Comment by erezrokah** [comment]
Hi @ethanosullivan, this should be fixed. Do you mind re-testing? `buildDir = "."` should stay the same

**Comment by ethanosullivan** [comment]
I checked all of my websites after redeplying them. I see the sitemap is working again, thanks.

Just as a heads up, the [README](https://github.com/netlify-labs/netlify-plugin-sitemap/blob/master/README.md) should be updated. It's showing up as `buildDir = "public"` and it should default to the root directory if that hasn't been implemented already.
